"""add instruments.vendor_lookup_name

Revision ID: 1ae5503ddec4
Revises: 321d11c83c31
Create Date: 2026-09-04 20:58:19.541150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae5503ddec4'
down_revision: Union[str, Sequence[str], None] = '321d11c83c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('vendor_lookup_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'vendor_lookup_name')
    # ### end Alembic commands ###
