"""initial schema

Revision ID: c41f8df6985c
Revises:
Create Date: 2026-09-04 16:42:55.610447

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c41f8df6985c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "factor_coverage",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("factor", sa.String(length=60), nullable=False),
        sa.Column("n_total", sa.Integer(), nullable=False),
        sa.Column("n_covered", sa.Integer(), nullable=False),
        sa.Column("coverage_pct", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factor_coverage")),
        sa.UniqueConstraint("as_of", "factor", name=op.f("uq_factor_coverage_as_of")),
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("symbols_processed", sa.Integer(), nullable=False),
        sa.Column("symbols_failed", sa.Integer(), nullable=False),
        sa.Column("rows_written", sa.Integer(), nullable=False),
        sa.Column("api_calls", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_runs")),
    )
    op.create_index(
        "ix_ingest_runs_job_started", "ingest_runs", ["job", "started_at"], unique=False
    )
    op.create_table(
        "instruments",
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sector", sa.String(length=120), nullable=True),
        sa.Column("industry", sa.String(length=160), nullable=True),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("bse_code", sa.String(length=20), nullable=True),
        sa.Column("groww_token", sa.String(length=40), nullable=True),
        sa.Column("groww_symbol", sa.String(length=60), nullable=True),
        sa.Column("lot_size", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("fundamentals_available", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("symbol", name=op.f("pk_instruments")),
    )
    op.create_index(op.f("ix_instruments_industry"), "instruments", ["industry"], unique=False)
    op.create_index(op.f("ix_instruments_isin"), "instruments", ["isin"], unique=False)
    op.create_index(op.f("ix_instruments_sector"), "instruments", ["sector"], unique=False)
    op.create_table(
        "provider_calls_daily",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("call_date", sa.Date(), nullable=False),
        sa.Column("endpoint", sa.String(length=80), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("cached_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_calls_daily")),
        sa.UniqueConstraint(
            "provider", "call_date", "endpoint", name=op.f("uq_provider_calls_daily_provider")
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_alerts_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_alerts_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(
        "ix_alerts_owner_triggered", "alerts", ["owner_id", "triggered_at"], unique=False
    )
    op.create_table(
        "announcements",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_announcements_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcements")),
        sa.UniqueConstraint(
            "symbol", "published_at", "headline", name=op.f("uq_announcements_symbol")
        ),
    )
    op.create_index(
        "ix_announcements_symbol_published",
        "announcements",
        ["symbol", "published_at"],
        unique=False,
    )
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("action_type", sa.String(length=30), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=True),
        sa.Column("record_date", sa.Date(), nullable=True),
        sa.Column("announced_date", sa.Date(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("percentage", sa.Float(), nullable=True),
        sa.Column("interim_or_final", sa.String(length=20), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_corporate_actions_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_actions")),
        sa.UniqueConstraint(
            "symbol", "action_type", "ex_date", "value", name=op.f("uq_corporate_actions_symbol")
        ),
    )
    op.create_index(
        "ix_corporate_actions_symbol_ex", "corporate_actions", ["symbol", "ex_date"], unique=False
    )
    op.create_table(
        "daily_bars",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_daily_bars_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_bars")),
        sa.UniqueConstraint("symbol", "date", name=op.f("uq_daily_bars_symbol")),
    )
    op.create_index(
        "ix_daily_bars_symbol_date_desc", "daily_bars", ["symbol", "date"], unique=False
    )
    op.create_table(
        "estimates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("measure", sa.String(length=8), nullable=False),
        sa.Column("period_type", sa.String(length=10), nullable=False),
        sa.Column("fiscal_year", sa.BigInteger(), nullable=False),
        sa.Column("fiscal_month", sa.BigInteger(), nullable=True),
        sa.Column("relative_period", sa.BigInteger(), nullable=True),
        sa.Column("actual", sa.Float(), nullable=True),
        sa.Column("mean_estimate", sa.Float(), nullable=True),
        sa.Column("high_estimate", sa.Float(), nullable=True),
        sa.Column("low_estimate", sa.Float(), nullable=True),
        sa.Column("num_estimates", sa.Float(), nullable=True),
        sa.Column("std_dev", sa.Float(), nullable=True),
        sa.Column("surprise_pct", sa.Float(), nullable=True),
        sa.Column("surprise_mean", sa.Float(), nullable=True),
        sa.Column("sue", sa.Float(), nullable=True),
        sa.Column("actual_report_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_estimates_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estimates")),
        sa.UniqueConstraint(
            "symbol",
            "measure",
            "period_type",
            "fiscal_year",
            "fiscal_month",
            name=op.f("uq_estimates_symbol"),
        ),
    )
    op.create_index("ix_estimates_symbol_measure", "estimates", ["symbol", "measure"], unique=False)
    op.create_table(
        "factor_values",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("factor", sa.String(length=60), nullable=False),
        sa.Column("raw", sa.Float(), nullable=True),
        sa.Column("zscore", sa.Float(), nullable=True),
        sa.Column("sector_zscore", sa.Float(), nullable=True),
        sa.Column("percentile", sa.Float(), nullable=True),
        sa.Column("decile", sa.Integer(), nullable=True),
        sa.Column("estimated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_factor_values_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factor_values")),
        sa.UniqueConstraint("symbol", "as_of", "factor", name=op.f("uq_factor_values_symbol")),
    )
    op.create_index(
        "ix_factor_values_asof_factor", "factor_values", ["as_of", "factor"], unique=False
    )
    op.create_table(
        "financial_statements",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("fiscal_end", sa.Date(), nullable=False),
        sa.Column("fiscal_year", sa.String(length=8), nullable=True),
        sa.Column("period_type", sa.String(length=10), nullable=False),
        sa.Column("statement", sa.String(length=4), nullable=False),
        sa.Column("line_key", sa.String(length=120), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("known_on", sa.Date(), nullable=False),
        sa.Column("known_on_estimated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_financial_statements_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_statements")),
        sa.UniqueConstraint(
            "symbol",
            "fiscal_end",
            "period_type",
            "statement",
            "line_key",
            name=op.f("uq_financial_statements_symbol"),
        ),
    )
    op.create_index(
        "ix_financial_statements_lookup",
        "financial_statements",
        ["symbol", "statement", "period_type", "fiscal_end"],
        unique=False,
    )
    op.create_table(
        "fundamental_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("known_on", sa.Date(), nullable=False),
        sa.Column("known_on_estimated", sa.Boolean(), nullable=False),
        sa.Column("pe_ttm", sa.Float(), nullable=True),
        sa.Column("pe_fy", sa.Float(), nullable=True),
        sa.Column("pe_normalized_fy", sa.Float(), nullable=True),
        sa.Column("pb_fy", sa.Float(), nullable=True),
        sa.Column("pb_q", sa.Float(), nullable=True),
        sa.Column("price_to_tangible_book_fy", sa.Float(), nullable=True),
        sa.Column("ps_ttm", sa.Float(), nullable=True),
        sa.Column("ps_fy", sa.Float(), nullable=True),
        sa.Column("peg", sa.Float(), nullable=True),
        sa.Column("dividend_yield", sa.Float(), nullable=True),
        sa.Column("dividend_yield_5y_avg", sa.Float(), nullable=True),
        sa.Column("price_to_fcf_fy", sa.Float(), nullable=True),
        sa.Column("price_to_cashflow_ttm", sa.Float(), nullable=True),
        sa.Column("ev_to_fcf_fy", sa.Float(), nullable=True),
        sa.Column("roe_fy", sa.Float(), nullable=True),
        sa.Column("roe_ttm", sa.Float(), nullable=True),
        sa.Column("roe_5y_avg", sa.Float(), nullable=True),
        sa.Column("roa_fy", sa.Float(), nullable=True),
        sa.Column("roa_5y_avg", sa.Float(), nullable=True),
        sa.Column("roi_fy", sa.Float(), nullable=True),
        sa.Column("roi_5y_avg", sa.Float(), nullable=True),
        sa.Column("asset_turnover_fy", sa.Float(), nullable=True),
        sa.Column("inventory_turnover_fy", sa.Float(), nullable=True),
        sa.Column("receivables_turnover_fy", sa.Float(), nullable=True),
        sa.Column("gross_margin_ttm", sa.Float(), nullable=True),
        sa.Column("gross_margin_5y_avg", sa.Float(), nullable=True),
        sa.Column("operating_margin_ttm", sa.Float(), nullable=True),
        sa.Column("operating_margin_5y_avg", sa.Float(), nullable=True),
        sa.Column("net_margin_ttm", sa.Float(), nullable=True),
        sa.Column("net_margin_5y_avg", sa.Float(), nullable=True),
        sa.Column("pretax_margin_ttm", sa.Float(), nullable=True),
        sa.Column("fcf_per_revenue_5y_avg", sa.Float(), nullable=True),
        sa.Column("debt_to_equity_fy", sa.Float(), nullable=True),
        sa.Column("debt_to_equity_q", sa.Float(), nullable=True),
        sa.Column("lt_debt_to_equity_fy", sa.Float(), nullable=True),
        sa.Column("current_ratio_fy", sa.Float(), nullable=True),
        sa.Column("quick_ratio_fy", sa.Float(), nullable=True),
        sa.Column("interest_coverage_ttm", sa.Float(), nullable=True),
        sa.Column("interest_coverage_fy", sa.Float(), nullable=True),
        sa.Column("payout_ratio_ttm", sa.Float(), nullable=True),
        sa.Column("net_debt_fy", sa.Float(), nullable=True),
        sa.Column("fcf_fy", sa.Float(), nullable=True),
        sa.Column("eps_growth_ttm", sa.Float(), nullable=True),
        sa.Column("eps_cagr_3y", sa.Float(), nullable=True),
        sa.Column("eps_cagr_5y", sa.Float(), nullable=True),
        sa.Column("eps_growth_q_yoy", sa.Float(), nullable=True),
        sa.Column("revenue_growth_ttm", sa.Float(), nullable=True),
        sa.Column("revenue_cagr_3y", sa.Float(), nullable=True),
        sa.Column("revenue_cagr_5y", sa.Float(), nullable=True),
        sa.Column("revenue_growth_q_yoy", sa.Float(), nullable=True),
        sa.Column("bvps_growth_5y", sa.Float(), nullable=True),
        sa.Column("ebitda_cagr_5y", sa.Float(), nullable=True),
        sa.Column("fcf_cagr_5y", sa.Float(), nullable=True),
        sa.Column("net_margin_growth_5y", sa.Float(), nullable=True),
        sa.Column("eps_ttm", sa.Float(), nullable=True),
        sa.Column("eps_fy", sa.Float(), nullable=True),
        sa.Column("eps_normalized_fy", sa.Float(), nullable=True),
        sa.Column("bvps_fy", sa.Float(), nullable=True),
        sa.Column("dps_ttm", sa.Float(), nullable=True),
        sa.Column("cfps_ttm", sa.Float(), nullable=True),
        sa.Column("revenue_ps_ttm", sa.Float(), nullable=True),
        sa.Column("cash_ps_fy", sa.Float(), nullable=True),
        sa.Column("revenue_ttm", sa.Float(), nullable=True),
        sa.Column("revenue_fy", sa.Float(), nullable=True),
        sa.Column("net_income_ttm", sa.Float(), nullable=True),
        sa.Column("net_income_fy", sa.Float(), nullable=True),
        sa.Column("ebitda_ttm", sa.Float(), nullable=True),
        sa.Column("ebitda_fy", sa.Float(), nullable=True),
        sa.Column("ebt_ttm", sa.Float(), nullable=True),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("beta", sa.Float(), nullable=True),
        sa.Column("week52_high", sa.Float(), nullable=True),
        sa.Column("week52_low", sa.Float(), nullable=True),
        sa.Column("avg_volume_10d", sa.Float(), nullable=True),
        sa.Column("avg_volume_3m", sa.Float(), nullable=True),
        sa.Column("rel_perf_13w", sa.Float(), nullable=True),
        sa.Column("rel_perf_26w", sa.Float(), nullable=True),
        sa.Column("rel_perf_52w", sa.Float(), nullable=True),
        sa.Column("rel_perf_ytd", sa.Float(), nullable=True),
        sa.Column("analyst_rating_mean", sa.Float(), nullable=True),
        sa.Column("analyst_count", sa.Float(), nullable=True),
        sa.Column("analyst_rating_mean_1m_ago", sa.Float(), nullable=True),
        sa.Column("analyst_rating_mean_3m_ago", sa.Float(), nullable=True),
        sa.Column("risk_std_dev", sa.Float(), nullable=True),
        sa.Column("risk_category", sa.String(length=60), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_fundamental_snapshots_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fundamental_snapshots")),
        sa.UniqueConstraint(
            "symbol", "snapshot_date", name=op.f("uq_fundamental_snapshots_symbol")
        ),
    )
    op.create_index(
        "ix_fundamental_snapshots_symbol_known",
        "fundamental_snapshots",
        ["symbol", "known_on"],
        unique=False,
    )
    op.create_table(
        "invites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code_hash", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redeemed_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_invites_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["redeemed_by"],
            ["users.id"],
            name=op.f("fk_invites_redeemed_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invites")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_invites_code_hash")),
    )
    op.create_table(
        "portfolios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("cash", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_portfolios_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolios")),
    )
    op.create_index(op.f("ix_portfolios_owner_id"), "portfolios", ["owner_id"], unique=False)
    op.create_table(
        "price_targets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("mean", sa.Float(), nullable=True),
        sa.Column("median", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("std_dev", sa.Float(), nullable=True),
        sa.Column("num_estimates", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_price_targets_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_targets")),
        sa.UniqueConstraint("symbol", "as_of", name=op.f("uq_price_targets_symbol")),
    )
    op.create_table(
        "shareholding",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("holding_date", sa.Date(), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("percentage", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_shareholding_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shareholding")),
        sa.UniqueConstraint(
            "symbol", "holding_date", "category", name=op.f("uq_shareholding_symbol")
        ),
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_preset", sa.Boolean(), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_strategies_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategies")),
        sa.UniqueConstraint("owner_id", "slug", "version", name=op.f("uq_strategies_owner_id")),
    )
    op.create_index(op.f("ix_strategies_owner_id"), "strategies", ["owner_id"], unique=False)
    op.create_table(
        "universes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=400), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_universes_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_universes")),
    )
    op.create_index(op.f("ix_universes_owner_id"), "universes", ["owner_id"], unique=False)
    op.create_index(op.f("ix_universes_slug"), "universes", ["slug"], unique=True)
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
    )
    op.create_index(
        op.f("ix_user_sessions_token_hash"), "user_sessions", ["token_hash"], unique=True
    )
    op.create_index(
        "ix_user_sessions_user_expires", "user_sessions", ["user_id", "expires_at"], unique=False
    )
    op.create_table(
        "valuation_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("metric", sa.String(length=20), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_valuation_history_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_valuation_history")),
        sa.UniqueConstraint("symbol", "date", "metric", name=op.f("uq_valuation_history_symbol")),
    )
    op.create_table(
        "watchlists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_watchlists_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlists")),
        sa.UniqueConstraint("owner_id", "name", name=op.f("uq_watchlists_owner_id")),
    )
    op.create_index(op.f("ix_watchlists_owner_id"), "watchlists", ["owner_id"], unique=False)
    op.create_table(
        "backtest_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("strategy_id", sa.UUID(), nullable=True),
        sa.Column("params_hash", sa.String(length=64), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_backtest_jobs_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_backtest_jobs_strategy_id_strategies"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_jobs")),
    )
    op.create_index("ix_backtest_jobs_hash", "backtest_jobs", ["params_hash"], unique=False)
    op.create_index(op.f("ix_backtest_jobs_owner_id"), "backtest_jobs", ["owner_id"], unique=False)
    op.create_index(
        "ix_backtest_jobs_status_created", "backtest_jobs", ["status", "created_at"], unique=False
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("avg_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("opened_on", sa.Date(), nullable=False),
        sa.Column("closed_on", sa.Date(), nullable=True),
        sa.Column("thesis", sa.Text(), nullable=True),
        sa.Column("conviction", sa.String(length=20), nullable=True),
        sa.Column("target_weight", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("entry_factors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("review_on", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_positions_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_positions_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_index(
        "ix_positions_portfolio_symbol", "positions", ["portfolio_id", "symbol"], unique=False
    )
    op.create_table(
        "screen_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("strategy_id", sa.UUID(), nullable=True),
        sa.Column("universe_slug", sa.String(length=60), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_screen_runs_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_screen_runs_strategy_id_strategies"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_screen_runs")),
    )
    op.create_index(op.f("ix_screen_runs_owner_id"), "screen_runs", ["owner_id"], unique=False)
    op.create_table(
        "universe_members",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("universe_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_universe_members_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["universe_id"],
            ["universes.id"],
            name=op.f("fk_universe_members_universe_id_universes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_universe_members")),
        sa.UniqueConstraint("universe_id", "symbol", name=op.f("uq_universe_members_universe_id")),
    )
    op.create_index(
        op.f("ix_universe_members_symbol"), "universe_members", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_universe_members_universe_id"), "universe_members", ["universe_id"], unique=False
    )
    op.create_table(
        "watchlist_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("watchlist_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["instruments.symbol"],
            name=op.f("fk_watchlist_items_symbol_instruments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlists.id"],
            name=op.f("fk_watchlist_items_watchlist_id_watchlists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_items")),
        sa.UniqueConstraint("watchlist_id", "symbol", name=op.f("uq_watchlist_items_watchlist_id")),
    )
    op.create_table(
        "exit_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=False),
        sa.Column("stop_type", sa.String(length=20), nullable=True),
        sa.Column("stop_value", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("target_ladder", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("time_stop_on", sa.Date(), nullable=True),
        sa.Column("factor_decay_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
            name=op.f("fk_exit_plans_position_id_positions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exit_plans")),
        sa.UniqueConstraint("position_id", name=op.f("uq_exit_plans_position_id")),
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("traded_on", sa.Date(), nullable=False),
        sa.Column("fees", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
            name=op.f("fk_trades_position_id_positions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
    )
    op.create_index("ix_trades_position_date", "trades", ["position_id", "traded_on"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trades_position_date", table_name="trades")
    op.drop_table("trades")
    op.drop_table("exit_plans")
    op.drop_table("watchlist_items")
    op.drop_index(op.f("ix_universe_members_universe_id"), table_name="universe_members")
    op.drop_index(op.f("ix_universe_members_symbol"), table_name="universe_members")
    op.drop_table("universe_members")
    op.drop_index(op.f("ix_screen_runs_owner_id"), table_name="screen_runs")
    op.drop_table("screen_runs")
    op.drop_index("ix_positions_portfolio_symbol", table_name="positions")
    op.drop_table("positions")
    op.drop_index("ix_backtest_jobs_status_created", table_name="backtest_jobs")
    op.drop_index(op.f("ix_backtest_jobs_owner_id"), table_name="backtest_jobs")
    op.drop_index("ix_backtest_jobs_hash", table_name="backtest_jobs")
    op.drop_table("backtest_jobs")
    op.drop_index(op.f("ix_watchlists_owner_id"), table_name="watchlists")
    op.drop_table("watchlists")
    op.drop_table("valuation_history")
    op.drop_index("ix_user_sessions_user_expires", table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_token_hash"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_universes_slug"), table_name="universes")
    op.drop_index(op.f("ix_universes_owner_id"), table_name="universes")
    op.drop_table("universes")
    op.drop_index(op.f("ix_strategies_owner_id"), table_name="strategies")
    op.drop_table("strategies")
    op.drop_table("shareholding")
    op.drop_table("price_targets")
    op.drop_index(op.f("ix_portfolios_owner_id"), table_name="portfolios")
    op.drop_table("portfolios")
    op.drop_table("invites")
    op.drop_index("ix_fundamental_snapshots_symbol_known", table_name="fundamental_snapshots")
    op.drop_table("fundamental_snapshots")
    op.drop_index("ix_financial_statements_lookup", table_name="financial_statements")
    op.drop_table("financial_statements")
    op.drop_index("ix_factor_values_asof_factor", table_name="factor_values")
    op.drop_table("factor_values")
    op.drop_index("ix_estimates_symbol_measure", table_name="estimates")
    op.drop_table("estimates")
    op.drop_index("ix_daily_bars_symbol_date_desc", table_name="daily_bars")
    op.drop_table("daily_bars")
    op.drop_index("ix_corporate_actions_symbol_ex", table_name="corporate_actions")
    op.drop_table("corporate_actions")
    op.drop_index("ix_announcements_symbol_published", table_name="announcements")
    op.drop_table("announcements")
    op.drop_index("ix_alerts_owner_triggered", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("provider_calls_daily")
    op.drop_index(op.f("ix_instruments_sector"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_isin"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_industry"), table_name="instruments")
    op.drop_table("instruments")
    op.drop_index("ix_ingest_runs_job_started", table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_table("factor_coverage")
    # ### end Alembic commands ###
