"""add estimates.period_end

Revision ID: 321d11c83c31
Revises: c41f8df6985c
Create Date: 2026-09-04 19:24:27.057198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321d11c83c31'
down_revision: Union[str, Sequence[str], None] = 'c41f8df6985c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('period_end', sa.Date(), nullable=True))
    op.create_index(op.f('ix_estimates_period_end'), 'estimates', ['period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimates_period_end'), table_name='estimates')
    op.drop_column('estimates', 'period_end')
    # ### end Alembic commands ###
